#pragma once

/*
   Dimensions of "TimerOverlay.png"
*/
#define TEXTURE_WIDTH				13050.0f
#define TEXTURE_HEIGHT				8460.0f

/*
   Pixel positions in "TimerOverlay.png"
   Origin is top-left
*/

#define PIX_TIMER_LEFT					60.0f
#define PIX_TIMER_BOTTOM				5890.0f
#define PIX_TIMER_RIGHT					12980.0f
#define PIX_TIMER_TOP					70.0f
#define PIX_TIMER_WIDTH					(PIX_TIMER_RIGHT - PIX_TIMER_LEFT + 10.0f)
#define PIX_TIMER_HEIGHT				(PIX_TIMER_BOTTOM - PIX_TIMER_TOP + 10.0f)
#define PIX_TIMER_ASPECT				(PIX_TIMER_WIDTH / PIX_TIMER_HEIGHT)

#define PIX_BTN_CLOCK_LEFT				1620.0f
#define PIX_BTN_CLOCK_BOTTOM			1460.0f
#define PIX_BTN_CLOCK_RIGHT				3710.0f
#define PIX_BTN_CLOCK_TOP				270.0f

#define PIX_BTN_TIMER1_LEFT				4110.0f
#define PIX_BTN_TIMER1_BOTTOM			1460.0f
#define PIX_BTN_TIMER1_RIGHT			6200.0f
#define PIX_BTN_TIMER1_TOP				270.0f

#define PIX_BTN_TIMER2_LEFT				6600.0f
#define PIX_BTN_TIMER2_BOTTOM			1460.0f
#define PIX_BTN_TIMER2_RIGHT			8690.0f
#define PIX_BTN_TIMER2_TOP				270.0f

#define PIX_BTN_TIMER3_LEFT				9120.0f
#define PIX_BTN_TIMER3_BOTTOM			1460.0f
#define PIX_BTN_TIMER3_RIGHT			11210.0f
#define PIX_BTN_TIMER3_TOP				270.0f

#define PIX_BTN_HR_LEFT					1620.0f
#define PIX_BTN_HR_BOTTOM				5680.0f
#define PIX_BTN_HR_RIGHT				3260.0f
#define PIX_BTN_HR_TOP					4490.0f

#define PIX_BTN_MIN_LEFT				3600.0f
#define PIX_BTN_MIN_BOTTOM				5680.0f
#define PIX_BTN_MIN_RIGHT				5240.0f
#define PIX_BTN_MIN_TOP					4490.0f

#define PIX_BTN_SEC_LEFT				5600.0f
#define PIX_BTN_SEC_BOTTOM				5680.0f
#define PIX_BTN_SEC_RIGHT				7240.0f
#define PIX_BTN_SEC_TOP					4490.0f

#define PIX_BTN_CLR_LEFT				7580.0f
#define PIX_BTN_CLR_BOTTOM				5680.0f
#define PIX_BTN_CLR_RIGHT				9220.0f
#define PIX_BTN_CLR_TOP					4490.0f

#define PIX_BTN_RCL_LEFT				9570.0f
#define PIX_BTN_RCL_BOTTOM				5680.0f
#define PIX_BTN_RCL_RIGHT				11210.0f
#define PIX_BTN_RCL_TOP					4490.0f

#define PIX_BTN_PWR_LEFT				270.0f
#define PIX_BTN_PWR_BOTTOM				2820.0f
#define PIX_BTN_PWR_RIGHT				1460.0f
#define PIX_BTN_PWR_TOP					1630.0f

#define PIX_BTN_VOL_LEFT				270.0f
#define PIX_BTN_VOL_BOTTOM				4320.0f
#define PIX_BTN_VOL_RIGHT				1460.0f
#define PIX_BTN_VOL_TOP					3130.0f

#define PIX_BTN_STS_LEFT				11360.0f
#define PIX_BTN_STS_BOTTOM				4320.0f
#define PIX_BTN_STS_RIGHT				12760.0f
#define PIX_BTN_STS_TOP					1630.0f

#define PIX_ICO_BAT_LEFT				6480.0f
#define PIX_ICO_BAT_BOTTOM				8380.0f
#define PIX_ICO_BAT_RIGHT				6840.0f
#define PIX_ICO_BAT_TOP					7530.0f

#define PIX_ICO_BAR_LEFT				7530.0f
#define PIX_ICO_BAR_BOTTOM				7730.0f
#define PIX_ICO_BAR_RIGHT				9400.0f
#define PIX_ICO_BAR_TOP					7530.0f

#define PIX_ICO_VOL_BOTTOM				8350.0f
#define PIX_ICO_VOL_TOP					7450.0f
#define PIX_ICO_VOL0_LEFT				9460.0f
#define PIX_ICO_VOL0_RIGHT				10330.0f
#define PIX_ICO_VOL1_LEFT				10430.0f
#define PIX_ICO_VOL1_RIGHT				11060.0f
#define PIX_ICO_VOL2_LEFT				11130.0f
#define PIX_ICO_VOL2_RIGHT				11950.0f
#define PIX_ICO_VOL3_LEFT				12010.0f
#define PIX_ICO_VOL3_RIGHT				12990.0f

#define PIX_ICO_BIG_DIGIT_LEFT			220.0f
#define PIX_ICO_BIG_DIGIT_TOP			6000.0f
#define PIX_ICO_BIG_DIGIT_BOTTOM		7430.0f
#define PIX_ICO_BIG_DIGIT_WIDTH			1100.0f
#define PIX_ICO_BIG_COLON_LEFT			11220.0f
#define PIX_ICO_BIG_COLON_RIGHT			11730.0f

#define PIX_ICO_SMALL_DIGIT_LEFT		260.0f
#define PIX_ICO_SMALL_DIGIT_TOP			7540.0f
#define PIX_ICO_SMALL_DIGIT_BOTTOM		8110.0f
#define PIX_ICO_SMALL_DIGIT_WIDTH		420.0f

#define PIX_ICO_SET_LEFT				6900.0f
#define PIX_ICO_SET_BOTTOM				7770.0f
#define PIX_ICO_SET_RIGHT				7440.0f
#define PIX_ICO_SET_TOP					7530.0f

#define PIX_ICO_UP_LEFT					4590.0f
#define PIX_ICO_UP_BOTTOM				8090.0f
#define PIX_ICO_UP_RIGHT				4940.0f
#define PIX_ICO_UP_TOP					7560.0f

#define PIX_ICO_DN_LEFT					5050.0f
#define PIX_ICO_DN_BOTTOM				8090.0f
#define PIX_ICO_DN_RIGHT				5400.0f
#define PIX_ICO_DN_TOP					7560.0f

#define PIX_ICO_DNUP_LEFT				5500.0f
#define PIX_ICO_DNUP_BOTTOM				8090.0f
#define PIX_ICO_DNUP_RIGHT				6390.0f
#define PIX_ICO_DNUP_TOP				7520.0f

#define PIX_ICO_CLOSE_LEFT				6860.0f
#define PIX_ICO_CLOSE_BOTTOM			8390.0f
#define PIX_ICO_CLOSE_RIGHT				7350.0f
#define PIX_ICO_CLOSE_TOP				7900.0f

#define PIX_ICO_HAND_LEFT				7380.0f
#define PIX_ICO_HAND_BOTTOM				8410.0f
#define PIX_ICO_HAND_RIGHT				8010.0f
#define PIX_ICO_HAND_TOP				7780.0f

#define PIX_ICO_HANDDRAG_LEFT			8050.0f
#define PIX_ICO_HANDDRAG_BOTTOM			8440.0f
#define PIX_ICO_HANDDRAG_RIGHT			8680.0f
#define PIX_ICO_HANDDRAG_TOP			7810.0f

#define PIX_ICO_HANDRESIZE_LEFT			8740.0f
#define PIX_ICO_HANDRESIZE_BOTTOM		8420.0f
#define PIX_ICO_HANDRESIZE_RIGHT		9390.0f
#define PIX_ICO_HANDRESIZE_TOP			7780.0f

/*
   Button positions (ratio, 0 to 1) relative to displayed timer image 
   Top-left is (00.0f). Bottom-Right is (1,1)
*/

#define RATIO_BTN_CLOCK_LEFT		(PIX_BTN_CLOCK_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_CLOCK_BOTTOM		(PIX_BTN_CLOCK_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_CLOCK_RIGHT		(PIX_BTN_CLOCK_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_CLOCK_TOP			(PIX_BTN_CLOCK_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_TIMER1_LEFT		(PIX_BTN_TIMER1_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_TIMER1_BOTTOM		(PIX_BTN_TIMER1_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_TIMER1_RIGHT		(PIX_BTN_TIMER1_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_TIMER1_TOP		(PIX_BTN_TIMER1_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_TIMER2_LEFT		(PIX_BTN_TIMER2_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_TIMER2_BOTTOM		(PIX_BTN_TIMER2_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_TIMER2_RIGHT		(PIX_BTN_TIMER2_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_TIMER2_TOP		(PIX_BTN_TIMER2_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_TIMER3_LEFT		(PIX_BTN_TIMER3_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_TIMER3_BOTTOM		(PIX_BTN_TIMER3_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_TIMER3_RIGHT		(PIX_BTN_TIMER3_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_TIMER3_TOP		(PIX_BTN_TIMER3_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_PWR_LEFT			(PIX_BTN_PWR_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_PWR_BOTTOM		(PIX_BTN_PWR_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_PWR_RIGHT			(PIX_BTN_PWR_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_PWR_TOP			(PIX_BTN_PWR_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_VOL_LEFT			(PIX_BTN_VOL_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_VOL_BOTTOM		(PIX_BTN_VOL_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_VOL_RIGHT			(PIX_BTN_VOL_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_VOL_TOP			(PIX_BTN_VOL_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_STS_LEFT			(PIX_BTN_STS_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_STS_BOTTOM		(PIX_BTN_STS_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_STS_RIGHT			(PIX_BTN_STS_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_STS_TOP			(PIX_BTN_STS_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_HR_LEFT			(PIX_BTN_HR_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_HR_BOTTOM			(PIX_BTN_HR_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_HR_RIGHT			(PIX_BTN_HR_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_HR_TOP			(PIX_BTN_HR_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_MIN_LEFT			(PIX_BTN_MIN_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_MIN_BOTTOM		(PIX_BTN_MIN_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_MIN_RIGHT			(PIX_BTN_MIN_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_MIN_TOP			(PIX_BTN_MIN_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_SEC_LEFT			(PIX_BTN_SEC_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_SEC_BOTTOM		(PIX_BTN_SEC_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_SEC_RIGHT			(PIX_BTN_SEC_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_SEC_TOP			(PIX_BTN_SEC_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_CLR_LEFT			(PIX_BTN_CLR_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_CLR_BOTTOM		(PIX_BTN_CLR_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_CLR_RIGHT			(PIX_BTN_CLR_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_CLR_TOP			(PIX_BTN_CLR_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

#define RATIO_BTN_RCL_LEFT			(PIX_BTN_RCL_LEFT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_RCL_BOTTOM		(PIX_BTN_RCL_BOTTOM - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT
#define RATIO_BTN_RCL_RIGHT			(PIX_BTN_RCL_RIGHT - PIX_TIMER_LEFT)/PIX_TIMER_WIDTH
#define RATIO_BTN_RCL_TOP			(PIX_BTN_RCL_TOP - PIX_TIMER_TOP)/PIX_TIMER_HEIGHT

/*
   Icon draing positions (ratio, 0 to 1) relative to displayed timer image
   Top-left is (00.0f). Bottom-Right is (1,1)
*/

#define RATIO_ICO_BAT_LEFT			(1650.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAT_BOTTOM		(2750.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_BAT_RIGHT			(1990.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAT_TOP			(1900.0f/PIX_TIMER_HEIGHT)

#define RATIO_ICO_BAR_BOTTOM		(1840.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_BAR_TOP			(1650.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_BAR0_LEFT			(1680.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR0_RIGHT		(3530.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR1_LEFT			(4170.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR1_RIGHT		(6020.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR2_LEFT			(6660.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR2_RIGHT		(8510.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR3_LEFT			(9180.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_BAR3_RIGHT		(11030.0f/PIX_TIMER_WIDTH)

#define RATIO_ICO_VOL_BOTTOM		(4090.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_VOL_TOP			(3190.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_VOL_LEFT			(1650.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_VOL0_RIGHT		(2520.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_VOL1_RIGHT		(2280.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_VOL2_RIGHT		(2470.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_VOL3_RIGHT		(2630.0f/PIX_TIMER_WIDTH)

#define RATIO_ICO_BIG_DIGIT_WIDTH		(PIX_ICO_BIG_DIGIT_WIDTH / PIX_TIMER_WIDTH)
#define RATIO_ICO_SMALL_DIGIT_WIDTH		(PIX_ICO_SMALL_DIGIT_WIDTH / PIX_TIMER_WIDTH)
#define RATIO_ICO_BIG_DIGIT_HEIGHT		(PIX_ICO_BIG_DIGIT_BOTTOM - PIX_ICO_BIG_DIGIT_TOP + 10.0f)/PIX_TIMER_HEIGHT
#define RATIO_ICO_SMALL_DIGIT_HEIGHT	(PIX_ICO_SMALL_DIGIT_BOTTOM - PIX_ICO_SMALL_DIGIT_TOP + 10.0f)/PIX_TIMER_HEIGHT

#define RATIO_ICO_COLON_WIDTH			((PIX_ICO_BIG_COLON_RIGHT - PIX_ICO_BIG_COLON_LEFT + 10.0f) / PIX_TIMER_WIDTH)

#define RATIO_ICO_DISP_TIME_TOP			(2670.0f / PIX_TIMER_HEIGHT)
#define RATIO_ICO_DISP_TIME_LEFT		(3040.0f / PIX_TIMER_WIDTH)

#define RATIO_ICO_SET_LEFT			(2270.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_SET_BOTTOM		(2150.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_SET_RIGHT			(2830.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_SET_TOP			(1890.0f/PIX_TIMER_HEIGHT)

#define RATIO_ICO_UP_LEFT			(4910.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_UP_LEFT2			(4430.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_UP_BOTTOM			(2430.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_UP_RIGHT			(5280.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_UP_RIGHT2			(4800.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_UP_TOP			(1890.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_UP_SPACING		(RATIO_ICO_BAR3_LEFT - RATIO_ICO_BAR2_LEFT)

#define RATIO_ICO_DNUP_LEFT			(4640.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_DNUP_BOTTOM		(2460.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_DNUP_RIGHT		(5520.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_DNUP_TOP			(1890.0f/PIX_TIMER_HEIGHT)

#define RATIO_ICO_SECONDS_TOP		(1870.0f/PIX_TIMER_HEIGHT)

#define RATIO_ICO_CLOSE_LEFT		(570.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_CLOSE_BOTTOM		(1050.0f/PIX_TIMER_HEIGHT)
#define RATIO_ICO_CLOSE_RIGHT		(1060.0f/PIX_TIMER_WIDTH)
#define RATIO_ICO_CLOSE_TOP			(560.0f/PIX_TIMER_HEIGHT)

#define RATIO_LCD_LEFT				(1610.0f/PIX_TIMER_WIDTH)
#define RATIO_LCD_BOTTOM			(4200.0f/PIX_TIMER_HEIGHT)
#define RATIO_LCD_RIGHT				(11100.0f/PIX_TIMER_WIDTH)
#define RATIO_LCD_TOP				(1610.0f/PIX_TIMER_HEIGHT)

